version: '3'
services:
  app1:
    image: natanielpaiva/exemplo-image-springboot-local:latest
    container_name: app1
    ports:
      - "8081:8080"
    deploy:
      resources:
        limits:
          cpus: '1.60'
          memory: '3GB'

  app2:
    image: natanielpaiva/exemplo-image-springboot-local:latest
    container_name: app2
    ports:
      - "8082:8080"
    deploy:
      resources:
        limits:
          cpus: '1.60'
          memory: '3GB'

  nginx:
    image: nginx-custom:latest
    container_name: nginx
    ports:
      - "9999:9999"
    depends_on:
      - app1
      - app2
    build:
      context: .
      dockerfile: Dockerfile-nginx
    deploy:
      resources:
        limits:
          cpus: '0.15'
          memory: '0.5GB'